version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    restart: always
    container_name: workersapp
    volumes:
      - .:/workersapp
    depends_on:
      - db
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"


volumes:
  postgres_data: