# Generated by Django 4.0.2 on 2022-02-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('surname', models.CharField(max_length=24)),
                ('age', models.SmallIntegerField()),
                ('profession', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='./images/')),
            ],
        ),
    ]
